apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - env:
        - name: REDIS_ADMIN_PW
          valueFrom:
            secretKeyRef:
              key: REDIS_ADMIN_PW
              name: worker-secret
        - name: REDIS_EXECUTOR_PW
          valueFrom:
            secretKeyRef:
              key: REDIS_EXECUTOR_PW
              name: worker-secret
        - name: REDIS_SCHEDULER_PW
          valueFrom:
            secretKeyRef:
              key: REDIS_SCHEDULER_PW
              name: worker-secret
        image: gcr.io/cs-workers-dev/redis-python:latest
        lifecycle:
          postStart:
            exec:
              command:
              - python3
              - /home/redis_init.py
        name: master
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
