version: "3.9"

services:
  webbase:
    build:
      context: ./
      dockerfile: Dockerfile.base
    image: webbase

  web:
    container_name: cs-web
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code/
    ports:
      - "8000:8000"

    depends_on:
      - webbase