apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-admin
  namespace: default
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-admin
  namespace: default
subjects:
  - kind: ServiceAccount
    name: scheduler
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: job-admin
  apiGroup: rbac.authorization.k8s.io
