{{ if .Values.db.deploy_db }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workers-db
  name: workers-db
  namespace: {{ .Values.workers_namespace }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: workers-db
{{ end }}