apiVersion: v1
kind: Secret
metadata:
  name: workers-db-secret
type: Opaque
stringData:
  USER: {{ .Values.db.user }}
  PASSWORD: {{ .Values.db.password }}
  HOST: {{ .Values.db.host }}
  NAME: {{ .Values.db.name }}