apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-cleanup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-remove
  namespace: {{ .Values.project_namespace }}
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-remove
  namespace: {{ .Values.project_namespace }}
subjects:
  - kind: ServiceAccount
    name: job-cleanup
    namespace: {{ .Values.project_namespace }}
roleRef:
  kind: Role
  name: job-remove
  apiGroup: rbac.authorization.k8s.io
