apiVersion: v1
kind: Service
metadata:
  name: outputs-processor
  namespace: {{ .Values.workers_namespace }}
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: outputs-processor
