apiVersion: apps/v1
kind: Deployment
metadata:
  name: outputs-processor
  namespace: {{ .Values.workers_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outputs-processor
  template:
    metadata:
      labels:
        app: outputs-processor
    spec:
      serviceAccountName: outputs-processor
      containers:
        - name: outputs-processor
          image: "{{ .Values.registry }}/{{ .Values.project }}/outputs_processor:{{ .Values.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: BUCKET
              value: {{ .Values.bucket }}
            - name: PROJECT
              value: {{ .Values.project }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workers-redis-secret
                  key: PASSWORD
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 2G
      nodeSelector:
        component: api
