apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-worker-outputs
  namespace: {{ .Values.workers_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rq-worker-outputs
  template:
    metadata:
      labels:
        app: rq-worker-outputs
    spec:
      serviceAccountName: rq-worker
      containers:
        - name: rq-worker-outputs
          command:
            ["rq", "worker", "--with-scheduler", "-c", "cs_workers.services.rq_settings"]
          image: "{{ .Values.registry }}/{{ .Values.project }}/outputs_processor:{{ .Values.tag }}"
          env:
            - name: BUCKET
              value: {{ .Values.bucket }}
            - name: PROJECT
              value: {{ .Values.project }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workers-redis-secret
                  key: PASSWORD
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 2G
      nodeSelector:
        component: api
