apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-worker-outputs
  namespace: {{ .Values.workers_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rq-worker-outputs
  template:
    metadata:
      labels:
        app: rq-worker-outputs
    spec:
      serviceAccountName: rq-worker
      containers:
        - name: rq-worker-outputs
          command: ["rq", "worker", "--with-scheduler", "--url", "$(REDIS_URL)"]
          image: "{{ .Values.registry }}/{{ .Values.project }}/outputs_processor:{{ .Values.tag }}"
          env:
            - name: BUCKET
              value: {{ .Values.bucket }}
            - name: PROJECT
              value: {{ .Values.project }}
            - name: REDIS_URL
              value: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}"
      nodeSelector:
        component: api
