{{ if .Values.use_traefik }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-tls
  namespace: {{ .Values.workers_namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match:
      kind: Rule
      services:
        - name: api
          port: 80
  tls:
    certResolver: myresolver
{{ end }}