apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: scheduler
      containers:
        - name: scheduler
          image:
          ports:
            - containerPort: 8888
          env:
            - name: PROJECT
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: PROJECT
            - name: CS_CRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: CS_CRYPT_KEY
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_DB
                  optional: true
            - name: REDIS_USER
              value: scheduler
            - name: REDIS_PW
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_SCHEDULER_PW
      nodeSelector:
        component: api
