apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.workers_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: "{{ .Values.registry }}/{{ .Values.project }}/workers_api:{{ .Values.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: BUCKET
              value: "{{ .Values.bucket }}"
            - name: PROJECT
              value: "{{ .Values.project }}"
            - name: VIZ_HOST
              value: "{{ .Values.viz_host }}"
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: API_SECRET_KEY
            - name: BACKEND_CORS_ORIGINS
              value: '{{ .Values.api.allow_origins | toJson }}'
            - name: PROJECT_NAMESPACE
              value: '{{ .Values.project_namespace }}'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: NAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: HOST

      nodeSelector:
        component: api
