apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workers-api
  template:
    metadata:
      labels:
        app: workers-api
    spec:
      serviceAccountName: workers-api
      containers:
        - name: workers-api
          image: "{{ .Values.registry }}/{{ .Values.project }}/workers_api:{{ .Values.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: BUCKET
              value: "{{ .Values.bucket }}"
            - name: VIZ_HOST
              value: "{{ .Values.viz_host }}"
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: workers-api-secret
                  key: API_SECRET_KEY
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: NAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: workers-db-secret
                  key: HOST

      nodeSelector:
        component: api
