apiVersion: v1
kind: ServiceAccount
metadata:
  name: workers-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-admin
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-admin
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: workers-api
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: job-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viz-admin
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps", "", "traefik.containo.us"]
    resources: ["deployments", "services", "ingressroutes"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viz-admin
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: workers-api
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: viz-admin
  apiGroup: rbac.authorization.k8s.io
