apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: {{ .Values.workers_namespace }}
type: Opaque
stringData:
  API_SECRET_KEY: {{ .Values.api.secret_key }}
  {{ if .Values.api.github_token }}
  GITHUB_TOKEN: {{ .Values.api.github_token }}
  {{ end }}
