apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-deployment-cleanup
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: web
          containers:
            - name: web-deployment-cleanup
              image: # Uses web image and is filled in with script.
              command: ["/bin/bash", "-c"]
              # Creates a main-terminated file on exit.
              # Sleeps 10 seconds to make sure that the proxy started.
              # Runs the manage.py command.
              args:
                - |
                  trap "touch /tmp/pod/main-terminated" EXIT;
                  sleep 10;
                  python manage.py rm_stale_deployments --stale-after 1800
              volumeMounts:
                - mountPath: /tmp/pod
                  name: tmp-pod
              resources:
                requests:
                  memory: 0.5G
                  cpu: "0.5"
                limits:
                  memory: 0.5G
                  cpu: "0.5"

              env:
                - name: PORT
                  value: "8000"

                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: web-db-secret
                      key: host

                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: web-db-secret
                      key: username

                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: web-db-secret
                      key: password

                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: web-db-secret
                      key: database

                - name: DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: web-configmap
                      key: DEBUG
                      optional: true

                - name: LOCAL
                  valueFrom:
                    configMapKeyRef:
                      name: web-configmap
                      key: LOCAL
                      optional: true

                - name: BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: web-configmap
                      key: BUCKET

                - name: DEFAULT_CLUSTER_USER
                  valueFrom:
                    configMapKeyRef:
                      name: web-configmap
                      key: DEFAULT_CLUSTER_USER

                - name: DEFAULT_VIZ_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: web-configmap
                      key: DEFAULT_VIZ_HOST

                - name: DJANGO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: web-secret
                      key: DJANGO_SECRET_KEY

                - name: CS_CRYPT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: web-secret
                      key: WEB_CS_CRYPT_KEY

                - name: USE_STRIPE
                  valueFrom:
                    configMapKeyRef:
                      name: web-configmap
                      key: USE_STRIPE

                - name: STRIPE_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: web-secret
                      key: STRIPE_SECRET
                      optional: true

                - name: WEBHOOK_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: web-secret
                      key: WEBHOOK_SECRET
                      optional: true

                - name: MAILGUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: web-secret
                      key: MAILGUN_API_KEY
                      optional: true

                - name: SENTRY_API_DSN
                  valueFrom:
                    secretKeyRef:
                      name: web-secret
                      key: SENTRY_API_DSN
                      optional: true

          nodeSelector:
            component: web
          restartPolicy: Never
          volumes:
          - emptyDir: {}
            name: tmp-pod
      backoffLimit: 1