apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: web:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 2G
              cpu: "2"
            limits:
              memory: 2G
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /users/me/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: PORT
              value: "8000"

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: web-db-secret
                  key: host

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: web-db-secret
                  key: username

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: web-db-secret
                  key: password

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: web-db-secret
                  key: database

            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: DEBUG
                  optional: true

            - name: LOCAL
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: LOCAL
                  optional: true

            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: BUCKET

            - name: DEFAULT_CLUSTER_USER
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: DEFAULT_CLUSTER_USER

            - name: DEFAULT_VIZ_HOST
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: DEFAULT_VIZ_HOST

            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DJANGO_SECRET_KEY

            - name: CS_CRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: WEB_CS_CRYPT_KEY

            - name: USE_STRIPE
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: USE_STRIPE

            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STRIPE_SECRET
                  optional: true

            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: WEBHOOK_SECRET
                  optional: true

            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: MAILGUN_API_KEY
                  optional: true

            - name: SENTRY_API_DSN
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: SENTRY_API_DSN
                  optional: true
      nodeSelector:
        component: web
