apiVersion: v1
kind: ConfigMap
metadata:
  name: web-configmap
data:
  DATABASE_URL: "postgresql://db:5432/postgres"
  LOCAL: "true"
  BUCKET: cs-outputs-dev-private
  USE_STRIPE: "false"
  DEFAULT_CLUSTER_USER: "hdoupe"
  DEFAULT_VIZ_HOST: "devviz.compute.studio"
  DEBUG: "true"
