name: Dev Workers Deploy

on:
  push:
    branches:
      - dev
      - ci-api
    paths:
      - "workers/**"
      - "deploy/**"
      - ".github/workflows/dev-workers-deploy.yml"

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}

  GKE_PROJECT: ${{ secrets.DEV_GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.DEV_GKE_EMAIL }}
  GKE_ZONE: us-central1-c
  GKE_CLUSTER: cluster-1
  REGISTRY_HOSTNAME: gcr.io

  PROJECT: ${{ secrets.DEV_GKE_PROJECT }}
  TAG: ${{ github.sha }}

  CS_CONFIG: ${{ secrets.DEV_CS_CONFIG }}
  DEV_WORKERS_VALUES: ${{ secrets.DEV_WORKERS_VALUES }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./secrets
          python -m pip install -e ./workers
          python -m pip install -e ./deploy

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: $GKE_EMAIL
          service_account_key: ${{ secrets.DEV_GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          gcloud auth configure-docker

      - name: Set cs-config.yaml and values.yaml files.
        run: |
          echo $CS_CONFIG | base64 --decode > cs-config.yaml
          echo $DEV_WORKERS_VALUES | base64 --decode > ./workers/values.deploy.yaml

      - name: Build Docker Images
        run: |
          cs workers svc build

      - name: Push Docker Images
        run: |
          cs workers svc push

      # Apply updates to cluster
      - name: Deploy
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
          cd workers
          helm template cs-workers \
            --set project=$PROJECT \
            --set tag=$TAG \
            --set api.secret_key=$(cs secrets get WORKERS_API_SECRET_KEY) \
            --set db.password=$(cs secrets get WORKERS_DB_PASSWORD)  \
            --namespace workers \
            -f values.deploy.yaml | kubectl apply -f -
