apiVersion: apps/v1
kind: Deployment
metadata:
  name: outputs-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outputs-processor
  template:
    metadata:
      labels:
        app: outputs-processor
    spec:
      containers:
        - name: outputs-processor
          image:
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          env:
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: BUCKET
            - name: CS_URL
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: CS_URL
            - name: CS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: CS_API_TOKEN
      nodeSelector:
        component: api